import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Aashish',
      email: 'admin@example.com',
      password: bcrypt.hashSync('sheesh'),
      isAdmin: true,
    },
    {
      name: 'Nancy Lirot',
      email: 'nancylirot8@gmail.com',
      password: bcrypt.hashSync('nancy'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Adidas Shoes',
      slug: 'adidas-shoes-1',
      category: 'Shoes',
      image: '/images/adidas-shoes-1.jpg', // 679px × 829px
      price: 350,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 10,
      description: 'High quality shoes from adidas.',
    },
    {
      // _id: '2',
      name: 'Nike Shoes',
      slug: 'nike-shoes-1',
      category: 'Shoes',
      image: '/images/nike-shoes-1.jpg',
      price: 400,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 15,
      description: 'High quality shoes from Nike.',
    },
    {
      // _id: '3',
      name: 'Puma Shoes',
      slug: 'puma-shoes-1',
      category: 'Shoes',
      image: '/images/puma-shoes-1.jpg',
      price: 300,
      countInStock: 7,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 20,
      description: 'High quality shoes from Puma.',
    },
    {
      // _id: '4',
      name: 'Levis Pants',
      slug: 'levis-pants-1',
      category: 'Pants',
      image: '/images/levis-pants-1.jpg',
      price: 125,
      countInStock: 15,
      brand: 'Levis',
      rating: 4.6,
      numReviews: 30,
      description: 'High quality pants from Levis.',
    },
    {
      // _id: '5',
      name: 'Shirt for Men',
      slug: 'men-shirt-checkered-1',
      category: 'Shirts',
      image: '/images/men-shirt-checkered-1.jpg',
      price: 75,
      countInStock: 15,
      brand: 'Diesel',
      rating: 4.4,
      numReviews: 10,
      description: 'High quality shirt from Diesel.',
    },
    {
      // _id: '6',
      name: 'Argentina Home Kit',
      slug: 'jersey-argentina-1',
      category: 'Football Kits',
      image: '/images/jersey-argentina-1.jpg',
      price: 50,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 38,
      description: 'Get your Argentina Home Kit now!',
    },
    {
      // _id: '7',
      name: 'Portugal Home Kit',
      slug: 'jersey-portugal-1',
      category: 'Football Kits',
      image: '/images/jersey-portugal-1.jpg',
      price: 55,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.9,
      numReviews: 70,
      description: 'Get your Portugal Home Kit now!',
    },
    {
      // _id: '8',
      name: 'Floral Skirt',
      slug: 'women-skirt-floral-1',
      category: 'Skirts',
      image: '/images/women-skirt-floral-1.jpg',
      price: 110,
      countInStock: 15,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 7,
      description: 'Get your floral skirt now, ladies!',
    },
    {
      // _id: '9',
      name: 'Black Crop Top',
      slug: 'women-croptop-black-1',
      category: 'Croptops',
      image: '/images/women-croptop-black-1.jpg',
      price: 65,
      countInStock: 25,
      brand: 'Louis Vuitton',
      rating: 4.8,
      numReviews: 12,
      description: 'Get your black croptop now, ladies!',
    },
  ],
};
export default data;
